# Generated by GeoPulse CI on Tue Sep  9 13:51:50 UTC 2025.
  # DO NOT EDIT.

  FROM ubuntu:latest

  # Download archive
  ADD https://github.com/SC-GeoPulse/ci/releases/latest/download/geo geo

  # Load development secrets & copy for publish
  RUN --mount=type=secret,id=config_local_json,dst=/etc/secrets/config.local.json       cp /etc/secrets/config.local.json .

  WORKDIR /App

  COPY --from=build-env /App .
  ENTRYPOINT ["geo"]

  
